//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vts.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vts.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vol. frac..
        /// </summary>
        public static string ChromophoreCoefficientType_FractionalAbsorptionCoefficient {
            get {
                return ResourceManager.GetString("ChromophoreCoefficientType_FractionalAbsorptionCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μM.
        /// </summary>
        public static string ChromophoreCoefficientType_MolarAbsorptionCoefficient {
            get {
                return ResourceManager.GetString("ChromophoreCoefficientType_MolarAbsorptionCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHz-1.
        /// </summary>
        public static string DependentVariableAxisUnits_PerGHz {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerGHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-1.
        /// </summary>
        public static string DependentVariableAxisUnits_PerMM {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-3.
        /// </summary>
        public static string DependentVariableAxisUnits_PerMMCubed {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerMMCubed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-3 GHz-1.
        /// </summary>
        public static string DependentVariableAxisUnits_PerMMCubedPerGHz {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerMMCubedPerGHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-3 ns-1.
        /// </summary>
        public static string DependentVariableAxisUnits_PerMMCubedPerNS {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerMMCubedPerNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-1 GHz-1.
        /// </summary>
        public static string DependentVariableAxisUnits_PerMMPerGHz {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerMMPerGHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-1 ns-1.
        /// </summary>
        public static string DependentVariableAxisUnits_PerMMPerNS {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerMMPerNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-2.
        /// </summary>
        public static string DependentVariableAxisUnits_PerMMSquared {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerMMSquared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-2 GHz-1.
        /// </summary>
        public static string DependentVariableAxisUnits_PerMMSquaredPerGHz {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerMMSquaredPerGHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm-2 ns-1.
        /// </summary>
        public static string DependentVariableAxisUnits_PerMMSquaredPerNS {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerMMSquaredPerNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ns-1.
        /// </summary>
        public static string DependentVariableAxisUnits_PerNS {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_PerNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitless.
        /// </summary>
        public static string DependentVariableAxisUnits_Unitless {
            get {
                return ResourceManager.GetString("DependentVariableAxisUnits_Unitless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(fx,z).
        /// </summary>
        public static string FluenceSolutionDomainType_FluenceofFx {
            get {
                return ResourceManager.GetString("FluenceSolutionDomainType_FluenceofFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(fx,ft).
        /// </summary>
        public static string FluenceSolutionDomainType_FluenceofFxAndFt {
            get {
                return ResourceManager.GetString("FluenceSolutionDomainType_FluenceofFxAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(fx,t,z).
        /// </summary>
        public static string FluenceSolutionDomainType_FluenceofFxAndT {
            get {
                return ResourceManager.GetString("FluenceSolutionDomainType_FluenceofFxAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(ρ,z).
        /// </summary>
        public static string FluenceSolutionDomainType_FluenceofRho {
            get {
                return ResourceManager.GetString("FluenceSolutionDomainType_FluenceofRho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(ρ,ft,z).
        /// </summary>
        public static string FluenceSolutionDomainType_FluenceofRhoAndFt {
            get {
                return ResourceManager.GetString("FluenceSolutionDomainType_FluenceofRhoAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(ρ,t,z).
        /// </summary>
        public static string FluenceSolutionDomainType_FluenceofRhoAndT {
            get {
                return ResourceManager.GetString("FluenceSolutionDomainType_FluenceofRhoAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∂R/∂g.
        /// </summary>
        public static string ForwardAnalysisType_dRdG {
            get {
                return ResourceManager.GetString("ForwardAnalysisType_dRdG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∂R/∂IV.
        /// </summary>
        public static string ForwardAnalysisType_dRdIV {
            get {
                return ResourceManager.GetString("ForwardAnalysisType_dRdIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∂R/∂μa.
        /// </summary>
        public static string ForwardAnalysisType_dRdMua {
            get {
                return ResourceManager.GetString("ForwardAnalysisType_dRdMua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∂R/∂μs&apos;.
        /// </summary>
        public static string ForwardAnalysisType_dRdMusp {
            get {
                return ResourceManager.GetString("ForwardAnalysisType_dRdMusp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∂R/∂n.
        /// </summary>
        public static string ForwardAnalysisType_dRdN {
            get {
                return ResourceManager.GetString("ForwardAnalysisType_dRdN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string ForwardAnalysisType_R {
            get {
                return ResourceManager.GetString("ForwardAnalysisType_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to δ-P1 (Analytic).
        /// </summary>
        public static string ForwardSolverType_DeltaPOne {
            get {
                return ResourceManager.GetString("ForwardSolverType_DeltaPOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Diffusion (Analytic - Distributed Gaussian Source).
        /// </summary>
        public static string ForwardSolverType_DistributedGaussianSDA {
            get {
                return ResourceManager.GetString("ForwardSolverType_DistributedGaussianSDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Diffusion (Analytic - Distributed Line Source).
        /// </summary>
        public static string ForwardSolverType_DistributedPointSDA {
            get {
                return ResourceManager.GetString("ForwardSolverType_DistributedPointSDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaled Monte Carlo - Basic (g=0.8, n=1.4).
        /// </summary>
        public static string ForwardSolverType_MonteCarlo {
            get {
                return ResourceManager.GetString("ForwardSolverType_MonteCarlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaled Monte Carlo - NURBS (g=0.8, n=1.4).
        /// </summary>
        public static string ForwardSolverType_Nurbs {
            get {
                return ResourceManager.GetString("ForwardSolverType_Nurbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Diffusion (Analytic - Point Source).
        /// </summary>
        public static string ForwardSolverType_PointSDA {
            get {
                return ResourceManager.GetString("ForwardSolverType_PointSDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        public static string IndependentVariableAxis_Ft {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Ft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fx.
        /// </summary>
        public static string IndependentVariableAxis_Fx {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Fx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ρ.
        /// </summary>
        public static string IndependentVariableAxis_Rho {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Rho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        public static string IndependentVariableAxis_T {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to λ.
        /// </summary>
        public static string IndependentVariableAxis_Wavelength {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Wavelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHz.
        /// </summary>
        public static string IndependentVariableAxisUnits_GHz {
            get {
                return ResourceManager.GetString("IndependentVariableAxisUnits_GHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/mm.
        /// </summary>
        public static string IndependentVariableAxisUnits_InverseMM {
            get {
                return ResourceManager.GetString("IndependentVariableAxisUnits_InverseMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string IndependentVariableAxisUnits_MM {
            get {
                return ResourceManager.GetString("IndependentVariableAxisUnits_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nm.
        /// </summary>
        public static string IndependentVariableAxisUnits_NM {
            get {
                return ResourceManager.GetString("IndependentVariableAxisUnits_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ns.
        /// </summary>
        public static string IndependentVariableAxisUnits_NS {
            get {
                return ResourceManager.GetString("IndependentVariableAxisUnits_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μa Only.
        /// </summary>
        public static string InverseFitType_Mua {
            get {
                return ResourceManager.GetString("InverseFitType_Mua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μa and μs&apos;.
        /// </summary>
        public static string InverseFitType_MuaMusp {
            get {
                return ResourceManager.GetString("InverseFitType_MuaMusp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μa, μs&apos; and g.
        /// </summary>
        public static string InverseFitType_MuaMuspG {
            get {
                return ResourceManager.GetString("InverseFitType_MuaMuspG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μs&apos; Only.
        /// </summary>
        public static string InverseFitType_Musp {
            get {
                return ResourceManager.GetString("InverseFitType_Musp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A (Absorbed Energy).
        /// </summary>
        public static string MapType_AbsorbedEnergy {
            get {
                return ResourceManager.GetString("MapType_AbsorbedEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ (Fluence).
        /// </summary>
        public static string MapType_Fluence {
            get {
                return ResourceManager.GetString("MapType_Fluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd (Photon Hitting Density).
        /// </summary>
        public static string MapType_PhotonHittingDensity {
            get {
                return ResourceManager.GetString("MapType_PhotonHittingDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levenberg Marquardt.
        /// </summary>
        public static string OptimizerType_LevenbergMarquardt {
            get {
                return ResourceManager.GetString("OptimizerType_LevenbergMarquardt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levenberg Marquardt (mpfit).
        /// </summary>
        public static string OptimizerType_MPFitLevenbergMarquardt {
            get {
                return ResourceManager.GetString("OptimizerType_MPFitLevenbergMarquardt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulated Annealing.
        /// </summary>
        public static string OptimizerType_SimulatedAnnealing {
            get {
                return ResourceManager.GetString("OptimizerType_SimulatedAnnealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PlotNormalizationType_None {
            get {
                return ResourceManager.GetString("PlotNormalizationType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve.
        /// </summary>
        public static string PlotNormalizationType_RelativeToCurve {
            get {
                return ResourceManager.GetString("PlotNormalizationType_RelativeToCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string PlotNormalizationType_RelativeToMax {
            get {
                return ResourceManager.GetString("PlotNormalizationType_RelativeToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string ScalingType_Linear {
            get {
                return ResourceManager.GetString("ScalingType_Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log10.
        /// </summary>
        public static string ScalingType_Log {
            get {
                return ResourceManager.GetString("ScalingType_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intralipid [vol. frac.].
        /// </summary>
        public static string ScatteringType_Intralipid {
            get {
                return ResourceManager.GetString("ScatteringType_Intralipid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mie Particle.
        /// </summary>
        public static string ScatteringType_Mie {
            get {
                return ResourceManager.GetString("ScatteringType_Mie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Law [A*λ^(-b)].
        /// </summary>
        public static string ScatteringType_PowerLaw {
            get {
                return ResourceManager.GetString("ScatteringType_PowerLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(fx).
        /// </summary>
        public static string SolutionDomainType_RofFx {
            get {
                return ResourceManager.GetString("SolutionDomainType_RofFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(fx,ft).
        /// </summary>
        public static string SolutionDomainType_RofFxAndFt {
            get {
                return ResourceManager.GetString("SolutionDomainType_RofFxAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(fx,t).
        /// </summary>
        public static string SolutionDomainType_RofFxAndT {
            get {
                return ResourceManager.GetString("SolutionDomainType_RofFxAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(ρ).
        /// </summary>
        public static string SolutionDomainType_RofRho {
            get {
                return ResourceManager.GetString("SolutionDomainType_RofRho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(ρ,ft).
        /// </summary>
        public static string SolutionDomainType_RofRhoAndFt {
            get {
                return ResourceManager.GetString("SolutionDomainType_RofRhoAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R(ρ,t).
        /// </summary>
        public static string SolutionDomainType_RofRhoAndT {
            get {
                return ResourceManager.GetString("SolutionDomainType_RofRhoAndT", resourceCulture);
            }
        }
    }
}
