//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vts.MonteCarlo.Wcf.Test.MonteCarloServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonteCarloServiceProxy.IMonteCarloService")]
    public interface IMonteCarloService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonteCarloService/ExecuteBatch", ReplyAction="http://tempuri.org/IMonteCarloService/ExecuteBatchResponse")]
        bool[] ExecuteBatch(Vts.MonteCarlo.SimulationInput[] input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMonteCarloServiceChannel : Vts.MonteCarlo.Wcf.Test.MonteCarloServiceProxy.IMonteCarloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MonteCarloServiceClient : System.ServiceModel.ClientBase<Vts.MonteCarlo.Wcf.Test.MonteCarloServiceProxy.IMonteCarloService>, Vts.MonteCarlo.Wcf.Test.MonteCarloServiceProxy.IMonteCarloService {
        
        public MonteCarloServiceClient() {
        }
        
        public MonteCarloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonteCarloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonteCarloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonteCarloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool[] ExecuteBatch(Vts.MonteCarlo.SimulationInput[] input) {
            return base.Channel.ExecuteBatch(input);
        }
    }
}
