//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vts.SiteVisit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vts.SiteVisit.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Button_ClearAll {
            get {
                return ResourceManager.GetString("Button_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Newest.
        /// </summary>
        public static string Button_ClearNewest {
            get {
                return ResourceManager.GetString("Button_ClearNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string Button_ExportData {
            get {
                return ResourceManager.GetString("Button_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As Image.
        /// </summary>
        public static string Button_ExportImage {
            get {
                return ResourceManager.GetString("Button_ExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Fluence/Interrogation Map.
        /// </summary>
        public static string Button_GenerateFluence {
            get {
                return ResourceManager.GetString("Button_GenerateFluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Inverse Solver.
        /// </summary>
        public static string Button_InverseSolver {
            get {
                return ResourceManager.GetString("Button_InverseSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Initial Guess.
        /// </summary>
        public static string Button_PlotInitialGuess {
            get {
                return ResourceManager.GetString("Button_PlotInitialGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Measured Data.
        /// </summary>
        public static string Button_PlotMeasured {
            get {
                return ResourceManager.GetString("Button_PlotMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot μa Spectum.
        /// </summary>
        public static string Button_PlotMua {
            get {
                return ResourceManager.GetString("Button_PlotMua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot μs&apos; Spectrum.
        /// </summary>
        public static string Button_PlotMusPrime {
            get {
                return ResourceManager.GetString("Button_PlotMusPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Reflectance.
        /// </summary>
        public static string Button_PlotReflectance {
            get {
                return ResourceManager.GetString("Button_PlotReflectance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detector Temporal Frequency.
        /// </summary>
        public static string IndependentVariableAxis_Ft {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Ft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detector Spacial Frequency.
        /// </summary>
        public static string IndependentVariableAxis_Fx {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Fx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detector Positions.
        /// </summary>
        public static string IndependentVariableAxis_Rho {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Rho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection Time.
        /// </summary>
        public static string IndependentVariableAxis_T {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndependentVariableAxis_Wavelength.
        /// </summary>
        public static string IndependentVariableAxis_Wavelength {
            get {
                return ResourceManager.GetString("IndependentVariableAxis_Wavelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absorber Concentrations:.
        /// </summary>
        public static string Label_AbsorberConcentrations {
            get {
                return ResourceManager.GetString("Label_AbsorberConcentrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(fx,z).
        /// </summary>
        public static string Label_AOfFx {
            get {
                return ResourceManager.GetString("Label_AOfFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(fx,ft).
        /// </summary>
        public static string Label_AOfFxAndFt {
            get {
                return ResourceManager.GetString("Label_AOfFxAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(fx,t,z).
        /// </summary>
        public static string Label_AOfFxAndT {
            get {
                return ResourceManager.GetString("Label_AOfFxAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(ρ,z).
        /// </summary>
        public static string Label_AOfRho {
            get {
                return ResourceManager.GetString("Label_AOfRho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(ρ,ft,z).
        /// </summary>
        public static string Label_AOfRhoAndFt {
            get {
                return ResourceManager.GetString("Label_AOfRhoAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(ρ,t,z).
        /// </summary>
        public static string Label_AOfRhoAndT {
            get {
                return ResourceManager.GetString("Label_AOfRhoAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string Label_At {
            get {
                return ResourceManager.GetString("Label_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Concentration:.
        /// </summary>
        public static string Label_BloodConcentration {
            get {
                return ResourceManager.GetString("Label_BloodConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood volume [vol. frac.]:.
        /// </summary>
        public static string Label_BloodVolume {
            get {
                return ResourceManager.GetString("Label_BloodVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(fx,z).
        /// </summary>
        public static string Label_FluenceOfFx {
            get {
                return ResourceManager.GetString("Label_FluenceOfFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(fx,ft).
        /// </summary>
        public static string Label_FluenceOfFxAndFt {
            get {
                return ResourceManager.GetString("Label_FluenceOfFxAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(fx,t,z).
        /// </summary>
        public static string Label_FluenceOfFxAndT {
            get {
                return ResourceManager.GetString("Label_FluenceOfFxAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(ρ,z).
        /// </summary>
        public static string Label_FluenceOfRho {
            get {
                return ResourceManager.GetString("Label_FluenceOfRho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(ρ,ft,z).
        /// </summary>
        public static string Label_FluenceOfRhoAndFt {
            get {
                return ResourceManager.GetString("Label_FluenceOfRhoAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φ(ρ,t,z).
        /// </summary>
        public static string Label_FluenceOfRhoAndT {
            get {
                return ResourceManager.GetString("Label_FluenceOfRhoAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fwd Solver Engine:.
        /// </summary>
        public static string Label_ForwardSolver {
            get {
                return ResourceManager.GetString("Label_ForwardSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian Beam Diameter:.
        /// </summary>
        public static string Label_GaussianBeam {
            get {
                return ResourceManager.GetString("Label_GaussianBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold On.
        /// </summary>
        public static string Label_HoldOn {
            get {
                return ResourceManager.GetString("Label_HoldOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent Axis:.
        /// </summary>
        public static string Label_IndependentAxis {
            get {
                return ResourceManager.GetString("Label_IndependentAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inv Solver Engine:.
        /// </summary>
        public static string Label_InverseSolver {
            get {
                return ResourceManager.GetString("Label_InverseSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalization:.
        /// </summary>
        public static string Label_Normalization {
            get {
                return ResourceManager.GetString("Label_Normalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % noise.
        /// </summary>
        public static string Label_PercentNoise {
            get {
                return ResourceManager.GetString("Label_PercentNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(fx,z).
        /// </summary>
        public static string Label_PHDOfFx {
            get {
                return ResourceManager.GetString("Label_PHDOfFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(fx,ft,z).
        /// </summary>
        public static string Label_PHDOfFxAndFt {
            get {
                return ResourceManager.GetString("Label_PHDOfFxAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(fx,t,z).
        /// </summary>
        public static string Label_PHDOfFxAndT {
            get {
                return ResourceManager.GetString("Label_PHDOfFxAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(ρ,z).
        /// </summary>
        public static string Label_PHDOfRho {
            get {
                return ResourceManager.GetString("Label_PHDOfRho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(ρ,ft).
        /// </summary>
        public static string Label_PHDOfRhoAndFt {
            get {
                return ResourceManager.GetString("Label_PHDOfRhoAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phd(ρ,t,z).
        /// </summary>
        public static string Label_PHDOfRhoAndT {
            get {
                return ResourceManager.GetString("Label_PHDOfRhoAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Label:.
        /// </summary>
        public static string Label_PlotLabel {
            get {
                return ResourceManager.GetString("Label_PlotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (A = μs&apos; at 1000nm).
        /// </summary>
        public static string Label_PowerLawDefinitionA {
            get {
                return ResourceManager.GetString("Label_PowerLawDefinitionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ρ (Rho) Range:.
        /// </summary>
        public static string Label_RhoRange {
            get {
                return ResourceManager.GetString("Label_RhoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Label_ROfFx {
            get {
                return ResourceManager.GetString("Label_ROfFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Label_ROfFxAndFt {
            get {
                return ResourceManager.GetString("Label_ROfFxAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Label_ROfFxAndT {
            get {
                return ResourceManager.GetString("Label_ROfFxAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Label_ROfRho {
            get {
                return ResourceManager.GetString("Label_ROfRho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Label_ROfRhoAndFt {
            get {
                return ResourceManager.GetString("Label_ROfRhoAndFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Label_ROfRhoAndT {
            get {
                return ResourceManager.GetString("Label_ROfRhoAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Detector Separation:.
        /// </summary>
        public static string Label_SourceDetector {
            get {
                return ResourceManager.GetString("Label_SourceDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StO2 [frac.]:.
        /// </summary>
        public static string Label_StO2 {
            get {
                return ResourceManager.GetString("Label_StO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tissue Types:.
        /// </summary>
        public static string Label_TissueTypes {
            get {
                return ResourceManager.GetString("Label_TissueTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hb [μM]:.
        /// </summary>
        public static string Label_TotalHb {
            get {
                return ResourceManager.GetString("Label_TotalHb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis Spacing:.
        /// </summary>
        public static string Label_XAxisSpacing {
            get {
                return ResourceManager.GetString("Label_XAxisSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Axis Spacing:.
        /// </summary>
        public static string Label_YAxisSpacing {
            get {
                return ResourceManager.GetString("Label_YAxisSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z Range:.
        /// </summary>
        public static string Label_zRange {
            get {
                return ResourceManager.GetString("Label_zRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string Measurement_mm {
            get {
                return ResourceManager.GetString("Measurement_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string Value_A {
            get {
                return ResourceManager.GetString("Value_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        public static string Value_b {
            get {
                return ResourceManager.GetString("Value_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium n.
        /// </summary>
        public static string Value_MediumN {
            get {
                return ResourceManager.GetString("Value_MediumN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle n.
        /// </summary>
        public static string Value_ParticleN {
            get {
                return ResourceManager.GetString("Value_ParticleN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle radius.
        /// </summary>
        public static string Value_ParticleRadius {
            get {
                return ResourceManager.GetString("Value_ParticleRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Fraction.
        /// </summary>
        public static string Value_VolumeFraction {
            get {
                return ResourceManager.GetString("Value_VolumeFraction", resourceCulture);
            }
        }
    }
}
