using System;
using System.Collections.Generic;
using NUnit.Framework;
using Vts.Common;
using Vts.IO;
using Vts.MonteCarlo;
using Vts.MonteCarlo.Detectors;
using Vts.MonteCarlo.RayData;
using Vts.MonteCarlo.Sources;
using Vts.MonteCarlo.Tissues;

namespace Vts.Test.MonteCarlo.RayData
{
    [TestFixture]
    public class RayDatabaseTests
    {
        /// <summary>
        /// list of temporary files created by these unit tests
        /// </summary>
        readonly List<string> _listOfTestGeneratedFiles = new List<string>()
        {
            "testraydatabase",
            "testraydatabase.txt",
            "RayDiffuseReflectanceDatabase", // name has no "test" prefix, it is generated by the code so name fixed
            "RayDiffuseReflectanceDatabase.txt",
            //"file.txt", // file that captures output of MC simulation that usually goes to screen
        };

        /// <summary>
        /// Set up simulation specifying RayDatabase to be written
        /// </summary>
        [OneTimeSetUp]
        public void Setup_simulation_input_components()
        {
            // delete previously generated files
            Clear_folders_and_files();

            var input = new SimulationInput(
                100,
                "",
                new SimulationOptions(
                    0,
                    RandomNumberGeneratorType.MersenneTwister,
                    AbsorptionWeightingType.Continuous,
                    PhaseFunctionType.HenyeyGreenstein,
                    new List<DatabaseType>() { DatabaseType.RayDiffuseReflectance }, // SPECIFY DATABASE
                    false, // track statistics
                    0.0, // RR threshold -> 0 = no RR performed
                    1),
                new DirectionalPointSourceInput(
                    new Position(0.0, 0.0, 0.0),
                    new Direction(0.0, 0.0, 1.0),
                    1),
                new MultiLayerTissueInput(
                    new ITissueRegion[]
                    {
                            new LayerTissueRegion(
                                new DoubleRange(double.NegativeInfinity, 0.0),
                                new OpticalProperties(0.0, 1e-10, 0.0, 1.0)),
                            new LayerTissueRegion(
                                new DoubleRange(0.0, 20.0),
                                new OpticalProperties(0.01, 1.0, 0.8, 1.4)),
                            new LayerTissueRegion(
                                new DoubleRange(20.0, double.PositiveInfinity),
                                new OpticalProperties(0.0, 1e-10, 0.0, 1.0))
                    }),
                new List<IDetectorInput>()
                {
                    new ROfRhoAndTimeDetectorInput()
                    {
                        Rho = new DoubleRange(0.0, 10.0, 101),
                        Time = new DoubleRange(0.0, 1, 101)
                    }
                }              
            );
            new MonteCarloSimulation(input).Run();
        }

        /// <summary>
        /// clear all previously generated files.
        /// </summary>
        [OneTimeTearDown]
        public void Clear_folders_and_files()
        {
            // delete any previously generated files
            foreach (var file in _listOfTestGeneratedFiles)
            {
                FileIO.FileDelete(file);
            }
        }

        /// <summary>
        /// test to verify RayDatabaseWriter and RayDatabase.FromFile are working correctly.
        /// </summary>
        [Test]
        public void Validate_RayDatabase_Writer_and_FromFile_are_correct_when_using_WriteToFile()
        {
            const string databaseFileName = "testraydatabase";
            var firstRayDp = new RayDataPoint(
                    new Position(1, 1, 0),
                    new Direction(0, 1 / Math.Sqrt(2), -1 / Math.Sqrt(2)),
                    1.0);
            var secondRayDp = new RayDataPoint(
                    new Position(2, 2, 0),
                    new Direction(1 / Math.Sqrt(2), 0, -1 / Math.Sqrt(2)),
                    2.0);
            using (var dbWriter = new RayDatabaseWriter(
                VirtualBoundaryType.DiffuseReflectance, databaseFileName))
            {       
                dbWriter.Write(firstRayDp);
                dbWriter.Write(secondRayDp);
                dbWriter.Close();
            }
            // read back file written
            var rayDatabase = RayDatabase.FromFile(databaseFileName);
            Assert.That(rayDatabase.NumberOfElements, Is.EqualTo(2));

            // manually enumerate through the first two elements (same as foreach)
            // PhotonDatabase is designed so you don't have to have the whole thing
            // in memory, so .ToArray() loses the benefits of the lazy-load data points
            var enumerator = rayDatabase.DataPoints.GetEnumerator();
            // advance to the first point and test that the point is valid
            enumerator.MoveNext();
            var dp1 = enumerator.Current;
            Assert.That(dp1.Position.X == firstRayDp.Position.X, Is.True);
            Assert.That(dp1.Position.Y == firstRayDp.Position.Y, Is.True);
            Assert.That(dp1.Position.Z == firstRayDp.Position.Z, Is.True);
            Assert.That(dp1.Direction.Ux == firstRayDp.Direction.Ux, Is.True);
            Assert.That(dp1.Direction.Uy == firstRayDp.Direction.Uy, Is.True);
            Assert.That(dp1.Direction.Uz == firstRayDp.Direction.Uz, Is.True);
            Assert.That(dp1.Weight == firstRayDp.Weight, Is.True);
            // advance to the second point and test that the point is valid
            enumerator.MoveNext();
            var dp2 = enumerator.Current;
            Assert.That(dp2.Position.X == secondRayDp.Position.X, Is.True);
            Assert.That(dp2.Position.Y == secondRayDp.Position.Y, Is.True);
            Assert.That(dp2.Position.Z == secondRayDp.Position.Z, Is.True);
            Assert.That(dp2.Direction.Ux == secondRayDp.Direction.Ux, Is.True);
            Assert.That(dp2.Direction.Uy == secondRayDp.Direction.Uy, Is.True);
            Assert.That(dp2.Direction.Uz == secondRayDp.Direction.Uz, Is.True);
            Assert.That(dp2.Weight == secondRayDp.Weight, Is.True);
            enumerator.Dispose();
        }

        /// <summary>
        /// Test to verify RayDiffuseReflectanceDatabase generated by MCCL simulation
        /// executed in OneTimeSetup is written and that it has the correct contents.
        /// </summary>
        [Test]
        public void Validate_database_file_gets_written_by_MCCL_and_is_correct()
        {
            Assert.That(FileIO.FileExists("RayDiffuseReflectanceDatabase"), Is.True);
            // read the database from file, and verify the correct number of photons were written
            var rayDatabase = RayDatabase.FromFile("RayDiffuseReflectanceDatabase");

            Assert.That(rayDatabase.NumberOfElements, Is.EqualTo(88));
            var enumerator = rayDatabase.DataPoints.GetEnumerator();
            // advance to the first point and test that the point is valid
            enumerator.MoveNext();
            var dp1 = enumerator.Current;
            Assert.That(dp1.Position.Z, Is.EqualTo(0.0));
            Assert.That(Math.Abs(dp1.Weight - 0.021116) < 0.000001, Is.True);
            enumerator.Dispose();
        }
    }
}