using System;
using System.IO;
using System.Text.RegularExpressions;


public static class Helpers
{
    /// <summary>
    /// Constructs the full path to the CSV file generated by BenchmarkDotNet based on the execution mode.
    /// </summary>
    /// <param name="runInParallel">
    /// A boolean indicating whether the benchmark is running in parallel mode.
    /// If <c>true</c>, the path for the parallel benchmark CSV file is returned.
    /// Otherwise, the path for the non-parallel benchmark CSV file is returned.
    /// </param>
    /// <returns>
    /// The full path to the CSV file containing the benchmark results.
    /// </returns>
    private static string GetCsvFullPath(bool runInParallel)
    {
        var inputPath = Path.GetFullPath(Directory.GetCurrentDirectory());
        const string filePath = "\\BenchmarkDotNet.Artifacts\\results\\";
        var csvFile = runInParallel ?
            $"{typeof(ParallelMonteCarloSimulationBenchmarks).FullName}-report.csv" :
            $"{typeof(MonteCarloSimulationBenchmarks).FullName}-report.csv";
        return Path.GetFullPath(inputPath + filePath + csvFile);
    }

    /// <summary>
    /// Reads values from a CSV file located at the specified path.
    /// </summary>
    /// <param name="fullPath">The full path to the CSV file.</param>
    /// <returns>
    /// An array of strings representing the values read from the CSV file, or <c>null</c>
    /// if the file does not exist.
    /// </returns>
    private static string[] ReadValuesFromCsv(string fullPath)
    {
        if (!File.Exists(fullPath))
        {
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.WriteLine(@"CSV results file not found: {0}", fullPath);
            Console.ForegroundColor = ConsoleColor.White;
            return null;
        }

        using var reader = new StreamReader(fullPath);
        // read header line
        reader.ReadLine();
        // read data line
        var line = reader.ReadLine();
        var values = line?.Split(',');
        return values;
    }


    /// <summary>
    /// Extracts a double value from a specified index in an array of strings.
    /// </summary>
    /// <param name="values">The array of strings containing the values to parse.</param>
    /// <param name="index">The index of the value to extract within the array.</param>
    /// <returns>
    /// The parsed double value if successful; otherwise, <c>null</c> if the value cannot be parsed
    /// or if the index is out of bounds.
    /// </returns>
    private static double? ReadValue(string[] values, int index)
    {
        if (values.Length < 4) return null;
        // excise double from string of type "###.## ms"
        var valueMatch = Regex.Match(values[index], @"-?\d+(?:\.\d+)?").Value;
        if (!double.TryParse(valueMatch, out var value)) return null;
        return value;
    }
}
